//Mention ID here
@id = 656bd5b80d7024ad9734f8f5

GET http://localhost:6006/api/v1/event/{{id}}


### Get Event by ID Deployed

GET https://a9kd5c8zw6.execute-api.us-east-2.amazonaws.com/api/v1/event/{{id}}