//Mention ID here
@id = 6562f2ce1170773b924e6c70

GET http://localhost:6006/api/v1/event/{{id}}


### Get Event by ID Deployed

GET https://a9kd5c8zw6.execute-api.us-east-2.amazonaws.com/api/v1/event/{{id}}